---
title: "Assignment 2"
author: "Jenny Balmagia and Jessica Jagdeo"
date: "March 6, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```


```{r}
#Generate sample data for function

#Price - Table that has prices for different fish ($/lb)

fish_prices = data.frame(fish = c("Tuna","Swordfish","Salmon","Cod"), price = c(13, 9, 11, 6))

rownames(fish_prices) <- fish_prices[,1]

fish_price <- fish_prices %>% 
  select(price)

#Catch - Table that has the number caught for each fish species for each location 

possible_fish = c("Tuna", "Swordfish", "Salmon", "Cod")

fish_catch = data.frame(loc_A = sample(possible_fish, size = 20, replace = T), loc_B = sample(possible_fish, size = 20, replace = T), loc_C = sample(possible_fish, size = 20, replace = T)) 

# Jenny - I think we need to have a dataframe with counts, rather than with names:

fish_locations <- as.data.frame(possible_fish) %>% 
  mutate(Trinidad = sample(x = 10:50, size = 4, replace = TRUE),
         Jamaica = sample(x = 10:50, size = 4, replace = TRUE),
         Guyana = sample(x = 10:50, size = 4, replace = TRUE),
         Bahamas = sample(x = 10:50, size = 4, replace = TRUE),
         Barbados = sample(x = 10:50, size = 4, replace = TRUE))

rownames(fish_locations) <- fish_locations[,1]

fish_loc <- fish_locations %>% 
  select(-possible_fish)

#test

fish_rev(catch = fish_loc, price = fish_price) 

# Revenue per location and revenue per fish is working, but the max catch at each location is not working




```

